package interfaz;

import dominio.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Agustín Juárez - 236487
 * @author Eduardo Thevenet - 168626
 */
public class VentanaAgregarEquipo extends javax.swing.JFrame {

    private Sistema modelo;

    /**
     * Creates new form ventanaAgregarDocente
     */
    public VentanaAgregarEquipo() {
        initComponents();
    }

    public VentanaAgregarEquipo(Sistema modelo) {
        initComponents();
        this.modelo = modelo;
        this.setLocationRelativeTo(null);
        this.cargarListaEstudiantes();
        this.actualizarLista();
    }

    private void cargarListaEstudiantes() {

        DefaultListModel l = new DefaultListModel();
        for (Estudiante e : this.modelo.getEstudiantesSinEquipo()) {
            l.addElement(e);
        }
        jListEstudiantes.setModel(l);
    }

    private void actualizarLista() {

        DefaultListModel l = new DefaultListModel();
        if (this.modelo.getEquipos() != null) {
            for (Equipo eq : this.modelo.getEquipos()) {
                l.addElement(eq);
            }
        }
        jListEquipos.setModel(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 23), new java.awt.Dimension(0, 23), new java.awt.Dimension(32767, 23));
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEquipos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEstudiantes = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonAgregarEquipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Concurso de programación - Agregar Equipo");
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setText("Lista equipos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 20, 130, 24);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setText("Crear equipo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 20, 140, 24);
        getContentPane().add(filler1);
        filler1.setBounds(380, 80, 0, 200);

        jScrollPane1.setViewportView(jListEquipos);

        jScrollPane3.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(400, 70, 160, 210);

        jScrollPane2.setViewportView(jListEstudiantes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 70, 210, 210);

        jLabel2.setText("Estudiantes disponibles (Sin equipo asignado)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 50, 280, 14);

        jButtonAgregarEquipo.setText("Agregar");
        jButtonAgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarEquipo);
        jButtonAgregarEquipo.setBounds(290, 160, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEquipoActionPerformed
        List<String> selected = jListEstudiantes.getSelectedValuesList();
        if (selected.size() == 3) {
            ArrayList<Estudiante> integ = new ArrayList<>();
            int index = 1;

            for (int i = 0; i < selected.size(); i++) {
                Estudiante selectedE = this.modelo.getEstudianteCi(((Estudiante) selected.toArray()[i]).getCi());
                integ.add(selectedE);
            }

            if (this.modelo.getEquipos() != null) {
                index = this.modelo.getEquipos().size() + 1;
            }
            String nombreEquipo = "Equipo " + index;

            Equipo eq = new Equipo(nombreEquipo, integ);
            this.modelo.agregarEquipo(eq);

            this.actualizarLista();
            this.cargarListaEstudiantes();
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar 3 integrantes para el equipo.", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAgregarEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAgregarEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListEquipos;
    private javax.swing.JList<String> jListEstudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
