/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import dominio.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author agustinjuarez
 */
public class VentanaAgregarEstudiante extends javax.swing.JFrame {
    
    private Sistema modelo;
    /** Creates new form ventanaAgregarDocente */
    
    public VentanaAgregarEstudiante() {
        initComponents();
    }
    
    public VentanaAgregarEstudiante(Sistema modelo) {
        initComponents();
        this.modelo = modelo;
        this.setLocationRelativeTo(null);
        this.actualizarLista();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSemestreCrearEstudiante = new javax.swing.JTextField();
        jTextFieldNombreCrearEstudiante = new javax.swing.JTextField();
        jTextFieldCICrearEstudiante = new javax.swing.JTextField();
        jTextFieldNroCrearEstudiante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCrearEstudiante = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMailCrearEstudiante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEstudiantes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(250, 440));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setText("CREAR ESTUDIANTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 170, 24);

        jLabel2.setText("SEMESTRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 230, 100, 14);

        jTextFieldSemestreCrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSemestreCrearEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSemestreCrearEstudiante);
        jTextFieldSemestreCrearEstudiante.setBounds(170, 225, 190, 20);

        jTextFieldNombreCrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCrearEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreCrearEstudiante);
        jTextFieldNombreCrearEstudiante.setBounds(170, 65, 190, 20);

        jTextFieldCICrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCICrearEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCICrearEstudiante);
        jTextFieldCICrearEstudiante.setBounds(170, 105, 190, 20);
        getContentPane().add(jTextFieldNroCrearEstudiante);
        jTextFieldNroCrearEstudiante.setBounds(170, 185, 190, 20);

        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 70, 14);

        jLabel4.setText("C.I:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 19, 14);

        jLabel5.setText("MAIL:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 150, 28, 14);

        jButtonCrearEstudiante.setText("CREAR");
        jButtonCrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearEstudiante);
        jButtonCrearEstudiante.setBounds(110, 270, 180, 23);

        jLabel6.setText("NRO ESTUDIANTE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 190, 120, 14);
        getContentPane().add(jTextFieldMailCrearEstudiante);
        jTextFieldMailCrearEstudiante.setBounds(170, 145, 190, 20);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setText("LISTA ESTUDIANTES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 20, 160, 24);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(400, 40, 160, 2);

        jScrollPane1.setViewportView(jListEstudiantes);

        jScrollPane3.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(410, 70, 150, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCrearEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCrearEstudianteActionPerformed

    private void jTextFieldCICrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCICrearEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCICrearEstudianteActionPerformed

    private void jTextFieldSemestreCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSemestreCrearEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSemestreCrearEstudianteActionPerformed

    private void jButtonCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearEstudianteActionPerformed
        String nombre = jTextFieldNombreCrearEstudiante.getText();
        String mail = jTextFieldNroCrearEstudiante.getText();
        String ci = jTextFieldCICrearEstudiante.getText();
        String nroEstudiante = jTextFieldNroCrearEstudiante.getText();
        String semestre = jTextFieldSemestreCrearEstudiante.getText();
        
        Estudiante estudiante = new Estudiante(nombre,ci,mail,nroEstudiante,semestre);
        boolean ok = this.modelo.agregarEstudiante(estudiante);
        if(ok) {
            JOptionPane.showMessageDialog(null, "El Estudiante "+nombre+" se ha dado de alta en el sistema", "Informacion",JOptionPane.INFORMATION_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(null, "El Estudiante "+nombre+" ya se encuentra en el sistema.", "Informacion",JOptionPane.WARNING_MESSAGE);
        }
        System.out.println(this.modelo.getEstudiantes());
        
        actualizarLista();
        
    }//GEN-LAST:event_jButtonCrearEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarEstudiante().setVisible(true);
            }
        });
    }
    
    private void actualizarLista(){
        
        DefaultListModel l = new DefaultListModel();
        for(Estudiante e : this.modelo.getEstudiantes()){
            l.addElement(e);
        }
        jListEstudiantes.setModel(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListEstudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCICrearEstudiante;
    private javax.swing.JTextField jTextFieldMailCrearEstudiante;
    private javax.swing.JTextField jTextFieldNombreCrearEstudiante;
    private javax.swing.JTextField jTextFieldNroCrearEstudiante;
    private javax.swing.JTextField jTextFieldSemestreCrearEstudiante;
    // End of variables declaration//GEN-END:variables

}
