/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.*;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author agustinjuarez
 */
public class VentanaEstadisticas extends javax.swing.JFrame {

    private Sistema modelo;

    /**
     * Creates new form ventanaAgregarDocente
     */

    public VentanaEstadisticas() {
        initComponents();
    }

    public VentanaEstadisticas(Sistema modelo) {
        initComponents();
        this.modelo = modelo;
        this.setLocationRelativeTo(null);
        this.actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstadisticas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(250, 440));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setText("Estadísticas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 10, 140, 24);

        jTableEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ejercicio", "Cantidad OK", "Tiempo 1era ok"
            }
        ));
        jScrollPane2.setViewportView(jTableEstadisticas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 90, 480, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarLista() {

        DefaultTableModel model = new DefaultTableModel();
        jTableEstadisticas.setModel(model);

// Create a couple of columns 
        model.addColumn("Ejercicio");
        model.addColumn("cantidad OK");
        model.addColumn("Tiempo 1era ok");

// Append a row 
        
        for (int i = 0; i < this.modelo.getEstadisticas().length; i++) {
           model.addRow(this.modelo.getEstadisticas()[i]);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEstadisticas;
    // End of variables declaration//GEN-END:variables

}
