/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import dominio.*;
import java.io.*;
import java.util.Iterator;
/**
 *
 * @author agustinjuarez
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private Sistema modelo;
    /**
     * Creates new form Main2
     */
    public VentanaPrincipal() {
        initComponents();
    }

    public VentanaPrincipal(Sistema unSistema) {
        initComponents();
        this.modelo = unSistema;
        this.setLocationRelativeTo(null);
    }
   
    
    private void guardar(){
        try {
            FileOutputStream archivo = new FileOutputStream("Datos");
            ObjectOutputStream datos = new ObjectOutputStream(archivo);
            
            Iterator<Estudiante> itE = this.modelo.getEstudiantes().iterator();
            while(itE.hasNext()){
                Estudiante e = itE.next();
                datos.writeObject(e);
            }
            
            Iterator<Docente> itD = this.modelo.getDocentes().iterator();
            while(itD.hasNext()){
                Docente d = itD.next();
                datos.writeObject(d);
            }

            datos.close();
        } catch (Exception e) {
            // hacer algo
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        fileMenu = new javax.swing.JMenu();
        registroEstudianteMenu = new javax.swing.JMenuItem();
        registroDocenteMenu = new javax.swing.JMenuItem();
        registroEquipoMenu = new javax.swing.JMenuItem();
        registroProblemaMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        CargaIndividualMenu = new javax.swing.JMenuItem();
        CargaGlobalMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        VisualizacionMenu = new javax.swing.JMenuItem();
        EstadisticasMenu = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concurso de programacion");
        setBackground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/logo.png"))); // NOI18N

        jMenu3.setText("Sistema");

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        menuBar.add(jMenu3);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Registro");

        registroEstudianteMenu.setMnemonic('o');
        registroEstudianteMenu.setText("Estudiante");
        registroEstudianteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroEstudianteMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroEstudianteMenu);

        registroDocenteMenu.setMnemonic('s');
        registroDocenteMenu.setText("Docente");
        registroDocenteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroDocenteMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroDocenteMenu);

        registroEquipoMenu.setMnemonic('a');
        registroEquipoMenu.setText("Equipo");
        registroEquipoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroEquipoMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroEquipoMenu);

        registroProblemaMenu.setText("Problema");
        registroProblemaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProblemaMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroProblemaMenu);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Solucion");

        CargaIndividualMenu.setMnemonic('t');
        CargaIndividualMenu.setText("Carga individual");
        CargaIndividualMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaIndividualMenuActionPerformed(evt);
            }
        });
        editMenu.add(CargaIndividualMenu);

        CargaGlobalMenu.setMnemonic('y');
        CargaGlobalMenu.setText("Carga global");
        editMenu.add(CargaGlobalMenu);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Resultados");

        VisualizacionMenu.setMnemonic('c');
        VisualizacionMenu.setText("Visualizacion");
        helpMenu.add(VisualizacionMenu);

        EstadisticasMenu.setMnemonic('a');
        EstadisticasMenu.setText("Estadisticas");
        helpMenu.add(EstadisticasMenu);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel2)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void registroEstudianteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroEstudianteMenuActionPerformed
        VentanaAgregarEstudiante vent = new VentanaAgregarEstudiante(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroEstudianteMenuActionPerformed

    private void registroDocenteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroDocenteMenuActionPerformed
        VentanaAgregarDocente vent = new VentanaAgregarDocente(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroDocenteMenuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.guardar();
    }//GEN-LAST:event_formWindowClosing

    private void registroEquipoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroEquipoMenuActionPerformed
        VentanaAgregarEquipo vent = new VentanaAgregarEquipo(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroEquipoMenuActionPerformed

    private void registroProblemaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroProblemaMenuActionPerformed
        VentanaAgregarProblema vent = new VentanaAgregarProblema(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroProblemaMenuActionPerformed

    private void CargaIndividualMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaIndividualMenuActionPerformed
        VentanaCargaIndividual vent = new VentanaCargaIndividual(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_CargaIndividualMenuActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CargaGlobalMenu;
    private javax.swing.JMenuItem CargaIndividualMenu;
    private javax.swing.JMenuItem EstadisticasMenu;
    private javax.swing.JMenuItem VisualizacionMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registroDocenteMenu;
    private javax.swing.JMenuItem registroEquipoMenu;
    private javax.swing.JMenuItem registroEstudianteMenu;
    private javax.swing.JMenuItem registroProblemaMenu;
    // End of variables declaration//GEN-END:variables
    
}
