/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import dominio.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author agustinjuarez
 */
public class VentanaAgregarDocente extends javax.swing.JFrame {
    
    private Sistema modelo;

    /** Creates new form ventanaAgregarDocente */
    public VentanaAgregarDocente() {
        initComponents();
        this.actualizarLista();
    }
    
    public VentanaAgregarDocente(Sistema modelo) {
        initComponents();
        this.modelo = modelo;
        this.setLocationRelativeTo(null);
        this.actualizarLista();
    }
    
    private void actualizarLista(){
        
        DefaultListModel l = new DefaultListModel();
        for(Docente d : this.modelo.getDocentes()){
            l.addElement(d);
        }
        jListDocentes.setModel(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIngresoCrearDocente = new javax.swing.JTextField();
        jTextFieldNombreCrearDocente = new javax.swing.JTextField();
        jTextFieldCICrearDocente = new javax.swing.JTextField();
        jTextFieldMailCrearDocente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCrearDocente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 23), new java.awt.Dimension(0, 23), new java.awt.Dimension(32767, 23));
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDocentes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setText("LISTA DOCENTES");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 20, 160, 24);

        jLabel2.setText("AÑO INGRESO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 205, 100, 14);

        jTextFieldIngresoCrearDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresoCrearDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngresoCrearDocente);
        jTextFieldIngresoCrearDocente.setBounds(170, 200, 190, 20);

        jTextFieldNombreCrearDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCrearDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreCrearDocente);
        jTextFieldNombreCrearDocente.setBounds(170, 80, 190, 20);

        jTextFieldCICrearDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCICrearDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCICrearDocente);
        jTextFieldCICrearDocente.setBounds(170, 120, 190, 20);
        getContentPane().add(jTextFieldMailCrearDocente);
        jTextFieldMailCrearDocente.setBounds(170, 160, 190, 20);

        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 85, 70, 14);

        jLabel4.setText("C.I:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 125, 19, 14);

        jLabel5.setText("MAIL:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 165, 28, 14);

        jButtonCrearDocente.setText("CREAR");
        jButtonCrearDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearDocente);
        jButtonCrearDocente.setBounds(110, 260, 180, 23);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setText("CREAR DOCENTE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 20, 140, 24);
        getContentPane().add(filler1);
        filler1.setBounds(380, 80, 0, 200);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 40, 340, 250);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(400, 40, 160, 2);

        jScrollPane1.setViewportView(jListDocentes);

        jScrollPane3.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(410, 70, 150, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreCrearDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCrearDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCrearDocenteActionPerformed

    private void jTextFieldCICrearDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCICrearDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCICrearDocenteActionPerformed

    private void jTextFieldIngresoCrearDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresoCrearDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngresoCrearDocenteActionPerformed

    private void jButtonCrearDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearDocenteActionPerformed
        String nombre = jTextFieldNombreCrearDocente.getText();
        String Mail = jTextFieldMailCrearDocente.getText();
        String ingreso = jTextFieldIngresoCrearDocente.getText();
        String CI = jTextFieldCICrearDocente.getText();
        Docente docente = new Docente(nombre,CI,Mail,ingreso);
        boolean ok = this.modelo.agregarDocente(docente);
        if(ok) {
            JOptionPane.showMessageDialog(null, "El Docente "+nombre+" se ha dado de alta en el sistema", "Informacion",JOptionPane.INFORMATION_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(null, "El Docente "+nombre+" ya se encuentra en el sistema.", "Informacion",JOptionPane.WARNING_MESSAGE);
        }
        System.out.println(this.modelo.getDocentes());
        
        this.actualizarLista();
        
    }//GEN-LAST:event_jButtonCrearDocenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonCrearDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListDocentes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCICrearDocente;
    private javax.swing.JTextField jTextFieldIngresoCrearDocente;
    private javax.swing.JTextField jTextFieldMailCrearDocente;
    private javax.swing.JTextField jTextFieldNombreCrearDocente;
    // End of variables declaration//GEN-END:variables

}
