package interfaz;

import dominio.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Agustín Juárez - 236487
 * @author Eduardo Thevenet - 168626
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Sistema modelo;

    public VentanaPrincipal() {
        initComponents();
    }

    public VentanaPrincipal(Sistema unSistema) {
        initComponents();
        this.modelo = unSistema;
        this.setLocationRelativeTo(null);
    }

    private void guardarSistema() {
        this.modelo.getHelper().guardarSistema(this.modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        registroEstudianteMenu = new javax.swing.JMenuItem();
        registroDocenteMenu = new javax.swing.JMenuItem();
        registroEquipoMenu = new javax.swing.JMenuItem();
        registroProblemaMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        CargaIndividualMenu = new javax.swing.JMenuItem();
        CargaGlobalMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        VisualizacionMenu = new javax.swing.JMenuItem();
        EstadisticasMenu = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concurso de programacion");
        setBackground(new java.awt.Color(0, 51, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/logo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(112, 112, 112))
        );

        jPanel3.setBackground(new java.awt.Color(102, 16, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/logoOrt.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Registro");

        registroEstudianteMenu.setMnemonic('o');
        registroEstudianteMenu.setText("Estudiante");
        registroEstudianteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroEstudianteMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroEstudianteMenu);

        registroDocenteMenu.setMnemonic('s');
        registroDocenteMenu.setText("Docente");
        registroDocenteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroDocenteMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroDocenteMenu);

        registroEquipoMenu.setMnemonic('a');
        registroEquipoMenu.setText("Equipo");
        registroEquipoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroEquipoMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroEquipoMenu);

        registroProblemaMenu.setText("Problema");
        registroProblemaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProblemaMenuActionPerformed(evt);
            }
        });
        fileMenu.add(registroProblemaMenu);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Solucion");

        CargaIndividualMenu.setMnemonic('t');
        CargaIndividualMenu.setText("Carga individual");
        CargaIndividualMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaIndividualMenuActionPerformed(evt);
            }
        });
        editMenu.add(CargaIndividualMenu);

        CargaGlobalMenu.setMnemonic('y');
        CargaGlobalMenu.setText("Carga global");
        CargaGlobalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaGlobalMenuActionPerformed(evt);
            }
        });
        editMenu.add(CargaGlobalMenu);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Resultados");

        VisualizacionMenu.setMnemonic('c');
        VisualizacionMenu.setText("Visualizacion");
        VisualizacionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizacionMenuActionPerformed(evt);
            }
        });
        helpMenu.add(VisualizacionMenu);

        EstadisticasMenu.setMnemonic('a');
        EstadisticasMenu.setText("Estadisticas");
        EstadisticasMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasMenuActionPerformed(evt);
            }
        });
        helpMenu.add(EstadisticasMenu);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroEstudianteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroEstudianteMenuActionPerformed
        VentanaAgregarEstudiante vent = new VentanaAgregarEstudiante(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroEstudianteMenuActionPerformed

    private void registroDocenteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroDocenteMenuActionPerformed
        VentanaAgregarDocente vent = new VentanaAgregarDocente(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroDocenteMenuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.guardarSistema();
    }//GEN-LAST:event_formWindowClosing

    private void registroEquipoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroEquipoMenuActionPerformed
        VentanaAgregarEquipo vent = new VentanaAgregarEquipo(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroEquipoMenuActionPerformed

    private void registroProblemaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroProblemaMenuActionPerformed
        VentanaAgregarProblema vent = new VentanaAgregarProblema(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_registroProblemaMenuActionPerformed

    private void CargaIndividualMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaIndividualMenuActionPerformed
        VentanaCargaIndividual vent = new VentanaCargaIndividual(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_CargaIndividualMenuActionPerformed

    private void VisualizacionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizacionMenuActionPerformed
        if (this.modelo.getEquipos().size() != 0 && this.modelo.getProblemas().size() != 0) {
            VentanaResultados vent = new VentanaResultados(this.modelo);
            this.modelo.addObserver(vent);
            vent.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay ningun equipo y problema registrado en el sistema", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
       
    }//GEN-LAST:event_VisualizacionMenuActionPerformed

    private void EstadisticasMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasMenuActionPerformed
        VentanaEstadisticas vent = new VentanaEstadisticas(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_EstadisticasMenuActionPerformed

    private void CargaGlobalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaGlobalMenuActionPerformed
        VentanaCargaGlobal vent = new VentanaCargaGlobal(this.modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_CargaGlobalMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CargaGlobalMenu;
    private javax.swing.JMenuItem CargaIndividualMenu;
    private javax.swing.JMenuItem EstadisticasMenu;
    private javax.swing.JMenuItem VisualizacionMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registroDocenteMenu;
    private javax.swing.JMenuItem registroEquipoMenu;
    private javax.swing.JMenuItem registroEstudianteMenu;
    private javax.swing.JMenuItem registroProblemaMenu;
    // End of variables declaration//GEN-END:variables

}
