package interfaz;

import dominio.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author Agustín Juárez - 236487
 * @author Eduardo Thevenet - 168626
 */
public class VentanaEnvios extends javax.swing.JFrame {

    private Sistema modelo;

    /**
     * Creates new form ventanaAgregarDocente
     */

    public VentanaEnvios() {
        initComponents();
    }

    public VentanaEnvios(Sistema modelo) {
        initComponents();
        this.modelo = modelo;
        this.setLocationRelativeTo(null);
        this.actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEnvios = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(250, 440));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setText("Lista envíos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 30, 140, 24);

        jScrollPane1.setViewportView(jListEnvios);

        jScrollPane3.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 70, 570, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarLista() {

        DefaultListModel l = new DefaultListModel();
        for (Envio e : this.modelo.getEnvios()) {
            l.addElement(e);
        }
        jListEnvios.setModel(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListEnvios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
